exports.teams = [1, 2, 3, 4, 5];
exports.offices = [1, 2, 3, 4, 5];
exports.companies = ['5*4', '3*9', '8*2', 'AI', '7*9'];
exports.roles = ["superAdmin", "companyboss", "officeboss", "teamboss", "member"];
exports.devFields = ["Web", "Mobile", "Architectural"];
exports.skills = ["Web", "Mobile", "Architectural"];
exports.themeColors = ['#7367F0', '#28C76F', '#EA5455', '#FF9F43', '#1E1E1E'];


const SITE_URL = "http://localhost:5050/";

exports.superAdminInformation =
{
    userID: 'superAdmin0303',
    password: 'superAdmin',
    role: 'superAdmin',
    status: true,
    dob: '2024-05-07T07:00:00.000Z',
    gender: 'male',
    name: 'Super Admin',
    organization: '7*9',
    department: 'Manage',
    team: '',
    avatar: SITE_URL + "/avatar/avatar.jpg",
    age: 100

};

exports.sampleUsers = [
    {
        userID: 'user1',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'SHU',
        organization: '3*9',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'


    },

    {
        userID: 'user2',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 2',
        organization: '3*9',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user3',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 3',
        organization: '3*9',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user4',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 4',
        organization: '3*9',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user5',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 5',
        organization: '3*9',
        department: 'Manage',
        team: '5',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user6',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 6',
        organization: '3*9',
        department: 'Manage',
        team: '5',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user7',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 7',
        organization: '3*9',
        department: 'Manage',
        team: '5',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user8',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 8',
        organization: '3*9',
        department: 'Manage',
        team: '5',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user9',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 9',
        organization: '3*9',
        department: 'Manage',
        team: '5',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },

    // 5*4
    {
        userID: 'user10',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 10',
        organization: '5*4',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user11',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 11',
        organization: '5*4',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user12',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 12',
        organization: '5*4',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user13',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 13',
        organization: '5*4',
        department: 'Manage',
        team: '1',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },


    {
        userID: 'user14',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 14',
        organization: '5*4',
        department: 'Manage',
        team: '2',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user15',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 15',
        organization: '5*4',
        department: 'Manage',
        team: '2',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    },
    {
        userID: 'user16',
        password: '123123',
        role: 'member',
        status: true,
        dob: '2024-05-07T07:00:00.000Z',
        gender: 'male',
        name: 'User 16',
        organization: '5*4',
        department: 'Manage',
        team: '2',
        avatar: SITE_URL + "/avatar/avatar.jpg",
        age: 100,
        university: 'NDU',
        devYear: '10',
        tecLicense: 'Web developer',
        majorSubject: 'Control Engineering',
        language: 'English',
        tecLevel: 'Senior',
        Personalities: 'Type 0',
        devArea: 'Freelancer'
    }
];



